#!/bin/bash
# =============================================================================
# etcd Bootstrap Script
# =============================================================================
# Installs and configures etcd for PostgreSQL HA cluster.
# Template variables are injected by Terraform templatefile().
# =============================================================================

set -euxo pipefail

# Log all output
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

echo "=== Starting etcd bootstrap ==="
echo "Instance Name: ${instance_name}"
echo "etcd Version: ${etcd_version}"

# -----------------------------------------------------------------------------
# System Configuration
# -----------------------------------------------------------------------------

# Set hostname
hostnamectl set-hostname ${instance_name}

# Update system packages
dnf update -y

# Install required packages
dnf install -y jq aws-cli

# -----------------------------------------------------------------------------
# Install etcd
# -----------------------------------------------------------------------------

ETCD_VER=${etcd_version}
DOWNLOAD_URL=https://github.com/etcd-io/etcd/releases/download

echo "=== Installing etcd $ETCD_VER ==="

# Download and extract etcd
curl -L $${DOWNLOAD_URL}/$${ETCD_VER}/etcd-$${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd.tar.gz
tar xzvf /tmp/etcd.tar.gz -C /tmp
mv /tmp/etcd-$${ETCD_VER}-linux-amd64/etcd /usr/local/bin/
mv /tmp/etcd-$${ETCD_VER}-linux-amd64/etcdctl /usr/local/bin/
mv /tmp/etcd-$${ETCD_VER}-linux-amd64/etcdutl /usr/local/bin/
chmod +x /usr/local/bin/etcd*

# Create etcd user and directories
useradd -r -s /sbin/nologin etcd || true
mkdir -p /var/lib/etcd
mkdir -p /etc/etcd
chown -R etcd:etcd /var/lib/etcd

# -----------------------------------------------------------------------------
# Get Instance Metadata
# -----------------------------------------------------------------------------

# Get IMDSv2 token
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

# Get private IP
PRIVATE_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" \
  http://169.254.169.254/latest/meta-data/local-ipv4)

echo "Private IP: $PRIVATE_IP"

# -----------------------------------------------------------------------------
# Configure etcd
# -----------------------------------------------------------------------------

echo "=== Configuring etcd ==="

cat > /etc/etcd/etcd.conf << EOF
# etcd configuration for ${instance_name}
# Generated by Terraform user-data script

ETCD_NAME="${instance_name}"
ETCD_DATA_DIR="/var/lib/etcd"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://$${PRIVATE_IP}:2379"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://$${PRIVATE_IP}:2380"
ETCD_INITIAL_CLUSTER="${initial_cluster}"
ETCD_INITIAL_CLUSTER_TOKEN="${cluster_token}"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_ENABLE_V2="false"
EOF

chown etcd:etcd /etc/etcd/etcd.conf
chmod 640 /etc/etcd/etcd.conf

# -----------------------------------------------------------------------------
# Create systemd Service
# -----------------------------------------------------------------------------

cat > /etc/systemd/system/etcd.service << 'EOF'
[Unit]
Description=etcd distributed key-value store
Documentation=https://etcd.io/docs/
After=network.target

[Service]
Type=notify
User=etcd
Group=etcd
EnvironmentFile=/etc/etcd/etcd.conf
ExecStart=/usr/local/bin/etcd
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

# -----------------------------------------------------------------------------
# Start etcd
# -----------------------------------------------------------------------------

echo "=== Starting etcd service ==="

systemctl daemon-reload
systemctl enable etcd
systemctl start etcd

# Wait for etcd to be ready
sleep 5

# Verify etcd is running
etcdctl endpoint health --endpoints=http://localhost:2379 || echo "Warning: etcd health check failed, may need cluster peers"

echo "=== etcd bootstrap completed ==="
